[package]
name = "substrata"
version = "0.2.0"
edition = "2021"
description = "Decentralized subscription payment protocol on Stellar Soroban"
license = "MIT"
repository = "https://github.com/Recurraa/Substrata-Contract"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { version = "23.0.2" }

[dev-dependencies]
soroban-sdk = { version = "23.0.2", features = ["testutils"] }

[features]
testutils = ["soroban-sdk/testutils"]
